# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{em-sofa}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["DeFirence", "Henry Hsu"]
  s.date = %q{2010-08-20}
  s.description = %q{A simple EventMachine based Ruby library for the TVRage API.}
  s.email = %q{defirence@defirence.za.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".yardopts",
     "LICENSE",
     "README.md",
     "Rakefile",
     "doc/Em-sofa/Mapping.html",
     "doc/Em-sofa/Mapping/ClassMethods.html",
     "doc/Em-sofa/Mapping/InstanceMethods.html",
     "doc/Em-sofa/TVRage.html",
     "doc/Em-sofa/TVRage/Episode.html",
     "doc/Em-sofa/TVRage/Schedule.html",
     "doc/Em-sofa/TVRage/Season.html",
     "doc/Em-sofa/TVRage/Show.html",
     "doc/Em-sofa/TVRage/Show/ShowNotFound.html",
     "doc/Em-sofa/Version.html",
     "doc/Sofa.html",
     "doc/_index.html",
     "doc/class_list.html",
     "doc/css/common.css",
     "doc/css/full_list.css",
     "doc/css/style.css",
     "doc/file.README.html",
     "doc/file_list.html",
     "doc/index.html",
     "doc/js/app.js",
     "doc/js/full_list.js",
     "doc/js/jquery.js",
     "doc/method_list.html",
     "doc/top-level-namespace.html",
     "lib/em-sofa.rb",
     "lib/em-sofa/mapping.rb",
     "lib/em-sofa/tvrage.rb",
     "lib/em-sofa/tvrage/episode.rb",
     "lib/em-sofa/tvrage/schedule.rb",
     "lib/em-sofa/tvrage/season.rb",
     "lib/em-sofa/tvrage/show.rb",
     "lib/em-sofa/version.rb",
     "spec/fixtures/tvrage/cases/castle.xml",
     "spec/fixtures/tvrage/cases/community.xml",
     "spec/fixtures/tvrage/cases/live_with_regis_and_kelly.xml",
     "spec/fixtures/tvrage/episode_list.xml",
     "spec/fixtures/tvrage/episode_list_one_season.xml",
     "spec/fixtures/tvrage/episode_list_two_episodes.xml",
     "spec/fixtures/tvrage/full_schedule.xml",
     "spec/fixtures/tvrage/full_show_info.xml",
     "spec/fixtures/tvrage/quickinfo.html",
     "spec/fixtures/tvrage/quickinfo_missing.html",
     "spec/fixtures/tvrage/search.xml",
     "spec/fixtures/tvrage/show_info.xml",
     "spec/fixtures/tvrage/show_info_blank.xml",
     "spec/fixtures/tvrage/single_episode.xml",
     "spec/sofa/mapping_spec.rb",
     "spec/sofa/tvrage/cases_spec.rb",
     "spec/sofa/tvrage/episode_spec.rb",
     "spec/sofa/tvrage/schedule_spec.rb",
     "spec/sofa/tvrage/season_spec.rb",
     "spec/sofa/tvrage/show_spec.rb",
     "spec/sofa/version_spec.rb",
     "spec/sofa_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/DeFirence/em-sofa}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{An EventMachine based Ruby library for the TVRage API.}
  s.test_files = [
    "spec/sofa/mapping_spec.rb",
     "spec/sofa/tvrage/cases_spec.rb",
     "spec/sofa/tvrage/episode_spec.rb",
     "spec/sofa/tvrage/schedule_spec.rb",
     "spec/sofa/tvrage/season_spec.rb",
     "spec/sofa/tvrage/show_spec.rb",
     "spec/sofa/version_spec.rb",
     "spec/sofa_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<em-http-request>, [">= 0"])
      s.add_runtime_dependency(%q<crack>, [">= 0"])
      s.add_development_dependency(%q<fakeweb>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
    else
      s.add_dependency(%q<em-http-request>, [">= 0"])
      s.add_dependency(%q<crack>, [">= 0"])
      s.add_dependency(%q<fakeweb>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
    end
  else
    s.add_dependency(%q<em-http-request>, [">= 0"])
    s.add_dependency(%q<crack>, [">= 0"])
    s.add_dependency(%q<fakeweb>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
  end
end

